formtips_trigger_action: hover
formtips_hoverintent: 1
formtips_timeout: 1000
formtips_interval: 500
formtips_sensitivity: 3
formtips_max_width: 500px
formtips_selectors: ''
_core:
  default_config_hash: zkoBdSop8yuw7o0FX3PSIqwrrh3bfJbho1vW87zx3eE
